Add simple model and linearization (#138)
* Add simple model

* Working simple model

* Linearize the model

* Fix precompilation

* Working precompilation

* Succesful lin

* Create linearization problem

* Make simple model even simpler

* Stable example

* Working simple example

* Update input output

* Move init unknowns

* Initialize with tether acc

* Reliable in out function

* Add a prob version as check/baseline

* Compare step functions

* Compare step functions

* Add back try catch

* Add name and move functions

* Add polars

* Downgrade MTK

* Passing test with reused model

* Fix heading calculation

* Check for plot

* Check for plot

* Add fields to s

* Add fields

* Fix state lin

* Add s from set

* Lower accuracy

* Add angle of attack

* Add symbolic aoa

* Add todo

* Fix version name

* Fix example

* Update MTK

* Quasi-static init

* Fix init bug

* Two working examples

* Working integ input-output

* Show that reinit is possible

* Add non-adaptive optioin

* Add simple twist angle

* Add simple twist

* Define var

* Fix bug

* Add front frac var

* Rotate around le

* Working ram and simple ram example

* Not all need compression frac

* Very fast

* Fix example

* Updade nonlinearsolve

* Fix ram test

* Update packages

* Better initial state

* Fixed omega z

* Small fixes

* Fix first init bug

* Add julia version arg

* Fix test and example

* Improve scripts

* Delete old prob defaults

* Rebuild sys

* Fix test and stiff unknowns

* Align z axis

* Example working well

* Working example

* Short SysState function

* Add more relax

* Fast non adaptive

* Use new sysstate fields

* Use default init alg

* Update for simple

* Working input output

* Tests pass

* Working examples

* Remove unneccesary show

* Update manifests

* Add discrete example

* Small fixes

* Add linear model

* Update operating point

* Actually update op

* Fix lin

* Set lin set_values

* Add vsm to lin

* Fix initial set

* Fix stupid bug

* Add turn rate

* Dont remake

* Fixed nonstiff

* Improve linearize

* Add nonstiff

* Fix bug

* Add measurements

* Correct lin setters

* Fix bug

* Fix tests

* Update default manifest

* Add test_plan.md

* Fix precompile script

* Update manifest

* Fix type bug

* Improve tether init

* Fix prob name

* Update test_plan.md

* Update name

* Add section Test again

* Update default bin file

* Add version cmd line arg

* Update docs

* Precompile full model

* Document test failure

* Delete bin files when creating a sysimage

* Minor change

* Update precompile.jl

* Add messages

* Update create_sys_image and precompile.jl

* New default manifest and new default problem

* Next try

* Fix info message

* Update manifest and xz file for 1.10

* Update message text

* Update WAIVER

* Fix licenses

* Add default manifest

* Delete default file

* Add create_xz_file

* Update default problem

* Update default manifest for current Julia version only

* Updated default bin file

* Fix license headers

* Fix license headers

* Improve message

* Always use the default Julia version

* Update test_plan

* Update message

* Update default problem

* Update test_plan

* Cleanup

* Delete license files, add them to REUSE.toml

* Update test plan

* Cleanup

* Add create_xz_file

---------

Co-authored-by: Uwe Fechner <fechner@aenarete.eu>
Co-authored-by: Uwe Fechner <uwe.fechner.msc@gmail.com>

diff --git a/bin/create_sys_image b/bin/create_sys_image
--- a/bin/create_sys_image
+++ b/bin/create_sys_image
@@ -1,16 +1,42 @@
 #!/bin/bash -eu
+# SPDX-FileCopyrightText: 2025 Uwe Fechner
+# SPDX-License-Identifier: MIT
 
 update=false
-if [[ $# -gt 0 ]]; then
-    if [[ $1 != "--update" ]]; then
-        echo "Invalid parameter! Use:"
-        echo "./create_sys_image"
-        echo "or"
-        echo "./create_sys_image --update"
-        exit 1
-    else
-        update=true
-    fi
+julia_version=""
+
+# Parse command line arguments
+while [[ $# -gt 0 ]]; do
+    case $1 in
+        --update)
+            update=true
+            shift
+            ;;
+        --version)
+            if [[ $# -lt 2 ]]; then
+                echo "Error: --version requires a version argument"
+                exit 1
+            fi
+            julia_version="$2"
+            shift 2
+            ;;
+        *)
+            echo "Invalid parameter! Use:"
+            echo "./create_sys_image"
+            echo "or"
+            echo "./create_sys_image --update"
+            echo "or"
+            echo "./create_sys_image --version 1.x"
+            exit 1
+            ;;
+    esac
+done
+
+# Remove the version switching code
+if [[ -n "$julia_version" ]]; then
+    JULIA_CMD="julia +$julia_version"
+else
+    JULIA_CMD="julia"
 fi
 
 if [[ $(basename $(pwd)) == "bin" ]]; then
@@ -68,7 +94,7 @@ if [[ $totalmem -lt 27000 ]]; then
     export JULIA_IMAGE_THREADS=1
 fi
 
-julia_version=$(julia --version | awk '{print($3)}')
+julia_version=$($JULIA_CMD --version | awk '{print($3)}')
 julia_major=${julia_version:0:3}
 if [[ $julia_major == "1.1" ]]; then
     julia_major=${julia_version:0:4} 
@@ -81,7 +107,7 @@ fi
 if test -f "kps-image-${julia_major}-${branch}.so"; then
     mv bin/kps-image-${julia_major}-${branch}.so kps-image-${julia_major}-${branch}.so.bak
 fi
-julia --startup-file=no -e "using Pkg; Pkg.add(\"TestEnv\")"
+$JULIA_CMD --startup-file=no -e "using Pkg; Pkg.add(\"TestEnv\")"
 
 if [[ $update == true ]]; then
     echo "Updating packages..."
@@ -98,11 +124,11 @@ if [[ $update == true ]]; then
             mv Manifest-v1.11.toml Manifest-v1.11.toml.bak
         fi
     fi
-    julia --startup-file=no --pkgimages=no --project -e "using TestEnv; TestEnv.activate(); using Pkg; Pkg.add(\"PyCall\"); Pkg.build(\"PyCall\")"
+    $JULIA_CMD --startup-file=no --pkgimages=no --project -e "using TestEnv; TestEnv.activate(); using Pkg; Pkg.add(\"PyCall\"); Pkg.build(\"PyCall\")"
     if [[ $PYTHON == "" ]]; then
-        julia --startup-file=no --pkgimages=no --project -e "using TestEnv; TestEnv.activate(); using Pkg; Pkg.add(\"Conda\"); using Conda; Conda.add(\"matplotlib\"); using ControlPlots"
+        $JULIA_CMD --startup-file=no --pkgimages=no --project -e "using TestEnv; TestEnv.activate(); using Pkg; Pkg.add(\"Conda\"); using Conda; Conda.add(\"matplotlib\"); using ControlPlots"
     fi
-    julia --startup-file=no --pkgimages=no --project -e "using Pkg; Pkg.update()"
+    $JULIA_CMD --startup-file=no --pkgimages=no --project -e "using Pkg; Pkg.update()"
     if [[ $julia_major == "1.10" ]]; then
         mv Manifest.toml Manifest-v1.10.toml
     else
@@ -118,10 +144,10 @@ else
     fi
 fi
 if [[ $update == true ]]; then
-    julia --startup-file=no --pkgimages=no --project -e "include(\"./test/create_sys_image.jl\");"
+    $JULIA_CMD --startup-file=no --pkgimages=no --project -e "include(\"./test/create_sys_image.jl\");"
 else
-    julia --startup-file=no --pkgimages=no --project -e "using Pkg; Pkg.instantiate();"
-    julia --startup-file=no --pkgimages=no --project -e "using TestEnv; TestEnv.activate(); include(\"./test/create_sys_image.jl\");"
+    $JULIA_CMD --startup-file=no --pkgimages=no --project -e "using Pkg; Pkg.instantiate();"
+    $JULIA_CMD --startup-file=no --pkgimages=no --project -e "using TestEnv; TestEnv.activate(); include(\"./test/create_sys_image.jl\");"
 fi
 
 if [[ $branch != "" ]]; then
@@ -133,19 +159,20 @@ if test -f $SOFILE; then
     mv $SOFILE $SOFILE.bak
 fi
 mv kps-image_tmp.so $SOFILE
-julia --startup-file=no  --project -e "using Pkg; Pkg.precompile(); Pkg.resolve()"
+$JULIA_CMD --startup-file=no  --project -e "using Pkg; Pkg.precompile(); Pkg.resolve()"
 if [ -d src ]; then
     cd src
     touch *.jl # make sure all modules get recompiled in the next step
     cd ..
 fi
-rm data/*.bin
-rm data/*.bin.default
+rm -f data/*.bin
+rm -f data/*.bin.default
 echo "Precompiling package KiteModels..."
-julia --startup-file=no --project -J $SOFILE -e "using KiteModels, KitePodModels, KiteUtils"
+$JULIA_CMD --startup-file=no --project -J $SOFILE -e "using KiteModels, KitePodModels, KiteUtils"
 echo "Precompiling package ControlPlots..."
 if [[ $branch != "" ]]; then
-    julia --startup-file=no --project -J $SOFILE -e "using TestEnv; TestEnv.activate(); using ControlPlots; using VortexStepMethod"
+    $JULIA_CMD --startup-file=no --project -J $SOFILE -e "using TestEnv; TestEnv.activate(); using ControlPlots; using VortexStepMethod"
 else
-    julia --startup-file=no --project -J $SOFILE -e "using ControlPlots; using VortexStepMethod"
+    $JULIA_CMD --startup-file=no --project -J $SOFILE -e "using ControlPlots; using VortexStepMethod"
 fi
+
